### PR TITLE
More Loanwords

### PR DESCRIPTION
**Pull request by AndersonCeci**
Hi!
I created a pull request containing some suggestions for the loanwords they are mostly from the Ottoman empire and are still used in the Albanian language

### CODE REVIEW

**Comment by AndiBraimllari** [comment]
Hi @AndersonCeci!

Thank you for your pull request. First thing that caught my eye, feel free to move yourself at the top of the contributors, as the list is alphabetically (case insensitive) sorted by username.

Regarding the added loanwords, one requirement, as also specified in the readme, is for them to have direct equivalents in Albanian. This is because we want keep a more reserved attitude for now at least (e.g. "jeshil" is widely used, and marking it would put most users off). Perhaps the entries to drop for now would be "javash", "inshallah", "pazar", "damar", "boş", "kanun", "nişan", "yeşil". Finally, don't forget to add the ë-s, e.g. in "e drejte", and don't add some entries that already exist, e.g. "akşam".

Before proceeding with having a closer look at the remaining entries, any other one you'd like to see dropped @KostaTB ?

**Comment by KostaTB** [comment]
@AndersonCeci Thank you so much for the file.
I agree with @AndiBraimllari on the above. One note I want to add is in regards to Kanun. Since it has become a part of the Albanian culture, 
my opinion would be to actually keep it as it is and not change it to "ligj", as for the most part when used, it directly refers to the cultural element. 
In relation to "ters" would you agree to add "fat i keq" as an alternative?

**Review by OpenCovenant — CHANGES_REQUESTED** [review]
Reorder your name in the contributors' list and address the aforementioned changes regarding the actual loanwords.

**Review by AndersonCeci — COMMENTED** [review]
Fixed the contributor list.
Removed the words "javash", "inshallah", "pazar", "damar", "boş", "kanun", "nişan", "yeşil", 
Added the "ë" in the word "e drejtë". 
Removed the duplicated word "akşam".
For the word "ters" I also added "fat i keq".

**Comment by AndiBraimllari** [comment]
Nice summary!

I'd say let's also drop "hallall" for now as it is used in quite a wide variety of contexts. Maybe we can add more alternatives to "avlli" and "sehir", and "yazik"? Don't forget to add "ë" to "mekat".
Also please delete the newly introduced new line at #482.

**Review by AndersonCeci — COMMENTED** [review]
Made the required changes added more alternatives to the words "avlli" and "sehir", and "yazik". 
And dropped the word "hallall".

**Comment by AndiBraimllari** [comment]
Nothing major from my side for now. Should we merge @KostaTB ?

**Comment by KostaTB** [comment]
Looks good to me! Thank you @AndersonCeci !

**Review by OpenCovenant — APPROVED** [review]

**Pull request merged**
